//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RemoteControl.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDS_NOT_ONLINE                  129
#define IDC_CLIENT_LIST                 130
#define IDD_PANE                        130
#define IDS_NOTIFY                      130
#define IDR_CLIENT_LIST                 131
#define IDS_CUR_CLIENT_NOT_ONLINE       131
#define IDP_SOCKETS_INIT_FAILED         132
#define IDI_DOC_MANAGE                  132
#define IDS_ONLINE                      133
#define IDI_TERMINAL                    133
#define IDS_CLOSED                      134
#define IDI_DESKTOP                     134
#define IDS_WAITE_FOR_CAPTURE_TIMEOUT   135
#define IDC_CMD_TABLE                   136
#define IDD_DIALOG1                     136
#define IDD_CMDTABLE                    136
#define IDS_SCREEN_SIZE                 136
#define IDI_SHUTDOWN                    137
#define IDS_APP_IS_RUNNING              137
#define IDD_DIALOG2                     138
#define IDD_OPTION                      138
#define IDS_SHUT_DOWN_FALIED            138
#define IDD_PUSH_SETTING                138
#define IDR_CMD_SHUTDOWN                139
#define IDS_RESTART_FALIED              139
#define IDS_LOGINOUT_FALIED             140
#define IDD_DIALOG3                     140
#define IDD_CMD_VIEW                    140
#define IDS_START_CMD_FAILED            141
#define IDR_ICON_MENU                   141
#define IDR_CMD_MENU                    142
#define IDS_PUSH                        142
#define IDD_SETTING                     143
#define IDS_CMD                         143
#define IDD_CMD_SETTING                 144
#define IDS_NOT_EXE_CMD                 144
#define IDR_REMOTECONTROLTYPE           145
#define IDS_MY_DOC                      145
#define IDI_NO_FULL_SCREEN              146
#define IDS_COMPUTER                    146
#define IDI_FULL_SCREEN                 147
#define IDS_DESKTOP                     147
#define IDD_DOC_MANAGE_DLG              148
#define IDS_DELETE_SUCCESS              148
#define IDI_MY_DOC                      149
#define IDS_DELETE_FAILED               149
#define IDI_COMPUTER                    150
#define IDS_DOWNLOAD_ERROR              150
#define IDS_UD_ERROR                    150
#define IDI_DIR                         151
#define IDS_UD_OVER                     151
#define IDI_DISK                        152
#define IDS_YES                         152
#define IDI_FILE                        153
#define IDS_NO                          153
#define IDI_DT                          154
#define IDR_FILE_TREE_MENU              155
#define IDD_DOWNLOAD_DLG                156
#define IDC_DESKTOP                     1002
#define IDC_TERMIMAL                    1003
#define IDC_TERMINAL                    1003
#define IDC_DOC_MANAGER                 1004
#define IDC_DESKTOP_CTRL                1005
#define IDC_SHUTDOWN                    1008
#define IDC_SLIDER1                     1009
#define IDC_SLIDE_QUALITY               1009
#define IDC_SCREEN_QUALITY              1009
#define IDC_EDIT1                       1015
#define IDC_ET_FLUENCY                  1015
#define IDC_SCREEN_FLUENCY              1015
#define IDC_ET_CMD_VIEW                 1015
#define IDC_ET_PREVIEW                  1015
#define IDC_SPIN1                       1016
#define IDC_SP_FLUENCY                  1016
#define IDC_FLUENCY_SPBIN               1016
#define IDC_FLUENCY_LABEL               1017
#define IDC_ST_QUALITY_NUM              1018
#define IDC_ST_QUALITY                  1019
#define IDC_CHECK1                      1020
#define IDC_LOCK_SEZI_RATIO             1020
#define IDC_EDIT2                       1021
#define IDC_SCREEN_SIZE_W               1021
#define IDC_EDIT3                       1022
#define IDC_SCREEN_SIZE_H               1022
#define IDC_MAX_SIZE                    1023
#define IDC_FLUENCY_TEXT                1025
#define IDC_TAB                         1027
#define IDC_APPLY                       1028
#define IDC_FONT                        1029
#define IDC_BG_ROUNF                    1030
#define IDC_FULL_SCREEN                 1032
#define IDC_FILE_TREE                   1033
#define IDC_DOWNLOAD_LIST               1035
#define IDC_INDEX_LABEL                 1036
#define ID_Menu                         32771
#define ID_FLUSH                        32772
#define ID_CLIENT_LIST                  32773
#define ID_PUSH_SERVER                  32774
#define ID_OPTION                       32775
#define ID_CANCEL_PUSH                  32776
#define ID_STOP_CTRL                    32787
#define ID_CLOSE_CLIENT                 32788
#define ID_SHUTDWON_CLIENT              32789
#define ID_RESARTE_CLIENT               32790
#define ID_LETTER_RAIN                  32791
#define ID_EXIT_CLIENT                  32792
#define ID_LOGIN_OUT                    32794
#define ID_ABOUT                        32797
#define ID_EXIT                         32798
#define ID_CMD                          32800
#define ID_COPY                         32807
#define ID_CUT                          32808
#define ID_PAST                         32809
#define ID_DELETE                       32810
#define ID_BACKROUND                    32811
#define ID_FONT                         32812
#define ID_CLIENT_CNT                   32813
#define ID_ONLINT_CLIENT_CNT            32814
#define ID_PUSH_CLINT_CNT               32815
#define ID_DOWNLOAD                     32822
#define ID_UPLOAD                       32823
#define ID__32824                       32824
#define ID_FILE_MANAGE                  32825
#define ID_32826                        32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
